export const EXCOS_DATA = [
  {
    id: 1,
    imageSrc: '/excos/olawale-ayoola.png',
    name: 'Olawale Ayoola',
    title: 'President',
    department: 'Electrical Engineering',
    phoneNumber: '+234 813 023 4284',
    email: 'Olawaleayoolaaa@gmail.com',
  },
  {
    id: 2,
    imageSrc: '/excos/mary-ukpete.png',
    name: 'Mary Ukpete',
    title: 'Vice President',
    department: 'Metallurgical and Materials Eng',
    phoneNumber: '+234 905 546 9197',
    email: 'maryukpete9@gmail.com',
  },
  {
    id: 3,
    imageSrc: '/excos/samuel-ogboro.png',
    name: 'Samuel Ogboro',
    title: 'General Secretary',
    department: 'Petroleum and Gas Engineering',
    phoneNumber: '+234 816 658 4997',
    email: 'ogborosam@gmail.com',
  },
  {
    id: 4,
    imageSrc: '/excos/damilare-aribisala.png',
    name: 'Damilare Aribisala',
    title: 'Public Relations Officer',
    department: 'Electrical/Electronics Engineering',
    phoneNumber: '+234 701 377 9723',
    email: 'Holuwadreya@gmail.com',
  },
  {
    id: 5,
    imageSrc: '/excos/david-fadeyi.png',
    name: 'David Fadeyi',
    title: 'Welfare Secretary',
    department: 'Electrical/Electronics Engineering',
    phoneNumber: '+234 902 121 1759',
    email: 'fadav4real@gmail.com',
  },
  {
    id: 6,
    imageSrc: '/excos/halimat-ozemoka.png',
    name: 'Halimat Ozemoka',
    title: 'Social Secretary',
    department: 'Systems Engineering',
    phoneNumber: '+234 708 012 1353',
    email: 'Olawale@gmail.com',
  },
  {
    id: 7,
    imageSrc: '/excos/soyoye-damilare.png',
    name: 'Soyoye Damilare',
    title: 'Sports Secretary',
    department: 'Surveying and Geoinformatics Eng',
    phoneNumber: '+234 814 292 1320',
    email: 'Olawale@gmail.com',
  },
  {
    id: 8,
    imageSrc: '/excos/wellens-michael.png',
    name: 'Wellens Michael',
    title: 'Financial Secretary',
    department: 'Electrical/Electronics Eng',
    phoneNumber: '+234 913 350 XXXX',
    email: 'michaelmfmwellens@gmail.com',
  },
  {
    id: 9,
    imageSrc: '/excos/treasure-adeolu.png',
    name: 'Treasure Adeolu',
    title: 'Treasurer',
    department: 'Mechanical Engineering',
    phoneNumber: '+234 815 724 7198',
    email: 'treasureadeolu95@gmail.com',
  },
  {
    id: 10,
    imageSrc: '/excos/lawal-olamide.png',
    name: 'Lawal Olamide',
    title: 'Assistant General Secretary',
    department: 'Metallurgical and Materials Eng',
    phoneNumber: '+234 903 154 9497',
    email: 'lawallvmide@gmail.com',
  },
];
